package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// executeJob runs a real (builtin) task-automation job that writes artifacts into
// OPM_DATA_DIR. Containerized Cursor-agent spawn remains follow-on work (orchestrator
// has docker.sock; opm-runner-task is still a placeholder image).
func executeJob(store *Store, j Job) {
	defer cleanupWorkspace(j.RunID)

	fail := func(msg string, err error) {
		now := nowUTC()
		j.State = "failed"
		j.Execution = "builtin"
		if err != nil {
			j.Error = err.Error()
		}
		j.Message = msg
		j.CompletedAt = &now
		_ = store.UpdateJob(j.ProjectID, j)
	}

	p, err := store.GetProject(j.ProjectID)
	if err != nil {
		fail("Builtin runner failed: project not found.", err)
		return
	}

	time.Sleep(50 * time.Millisecond)
	now := nowUTC()
	j.State = "starting"
	j.Execution = "builtin"
	j.Message = "Starting builtin runner: preparing workspace."
	j.StartedAt = &now
	_ = store.UpdateJob(j.ProjectID, j)

	workDir, err := prepareJobWorkspace(p, j.RunID)
	if err != nil {
		fail("Builtin runner failed while preparing workspace.", err)
		return
	}

	j, err = store.GetJob(j.ProjectID, j.RunID)
	if err != nil || j.State == "cancelled" {
		return
	}
	j.State = "running"
	j.Execution = "builtin"
	j.Message = fmt.Sprintf("Running builtin action %s…", j.Action)
	pct := 20
	j.ProgressPct = &pct
	_ = store.UpdateJob(j.ProjectID, j)

	_ = workDir // workspace prepared for future containerized runners

	resultMsg := ""
	switch j.Action {
	case "run-planning", "run-followup-planning":
		resultMsg, err = builtinPlanning(store, j)
	case "run-implementation":
		resultMsg, err = builtinImplementation(store, j)
	case "run-review":
		resultMsg, err = builtinReview(store, j)
	case "run-qa-fix":
		resultMsg, err = builtinQaFix(store, j)
	case "generate-changelog":
		resultMsg, err = builtinChangelog(store, j)
	case "run-roadmap-discovery", "run-roadmap-features", "run-ideation":
		resultMsg, err = builtinMetaNote(store, j)
	default:
		resultMsg = "Unknown action; no artifacts written."
		err = fmt.Errorf("unsupported action %q", j.Action)
	}

	j, gerr := store.GetJob(j.ProjectID, j.RunID)
	if gerr != nil || j.State == "cancelled" {
		return
	}
	done := nowUTC()
	if err != nil {
		j.State = "failed"
		j.Error = err.Error()
		j.Message = resultMsg
		j.Execution = "builtin"
		j.CompletedAt = &done
		_ = store.UpdateJob(j.ProjectID, j)
		return
	}
	j.State = "completed"
	j.Execution = "builtin"
	j.Message = resultMsg
	j.CompletedAt = &done
	pct = 100
	j.ProgressPct = &pct
	_ = store.UpdateJob(j.ProjectID, j)

	st := idleStatus()
	st.LastUpdate = done.Format(time.RFC3339)
	st.RunID = j.RunID
	_ = store.withProject(j.ProjectID, func(proj Project) error {
		return store.writeJSON(store.projectDir(proj)+"/status.json", st)
	})
}

func builtinPlanning(store *Store, j Job) (string, error) {
	if j.SpecID == "" {
		return "run-planning requires specId", fmt.Errorf("specId required")
	}
	task, err := store.GetTask(j.ProjectID, j.SpecID)
	if err != nil {
		return "Task not found", err
	}

	spec := fmt.Sprintf("# %s\n\n## Summary\n\n%s\n\n## Acceptance criteria\n\n- [ ] Core behavior works as described\n- [ ] Tests or verification steps documented\n- [ ] No regressions in related flows\n\n## Notes\n\nGenerated by OPM builtin planner (%s).\n",
		task.Title, nz(task.Description, "_No description provided._"), j.RunID)
	if err := store.PutSpecMarkdown(j.ProjectID, j.SpecID, spec); err != nil {
		return "Failed to write spec.md", err
	}

	plan := ImplementationPlan{
		Feature:          task.Title,
		WorkflowType:     "feature",
		ServicesInvolved: []string{"opm-api"},
		SpecFile:         "spec.md",
		Status:           "ready",
		PlanStatus:       "ready",
		FinalAcceptance: []string{
			"Behavior matches spec summary",
			"Verification steps completed",
		},
		Phases: []PlanPhase{
			{
				Phase: 1, Name: "Design", Type: "planning", ParallelSafe: false,
				Subtasks: []PlanSubtask{
					{ID: "1-0", Description: "Confirm scope and acceptance criteria", Status: "completed", Verification: "spec.md reviewed"},
				},
			},
			{
				Phase: 2, Name: "Implement", Type: "coding", ParallelSafe: false, DependsOn: []int{1},
				Subtasks: []PlanSubtask{
					{ID: "2-0", Description: "Implement core change for: " + task.Title, Status: "pending", FilesToModify: []string{}, Verification: "manual or automated check"},
					{ID: "2-1", Description: "Add or update tests / verification notes", Status: "pending", Verification: "tests pass or checklist done"},
				},
			},
			{
				Phase: 3, Name: "Review", Type: "review", ParallelSafe: false, DependsOn: []int{2},
				Subtasks: []PlanSubtask{
					{ID: "3-0", Description: "Self-review against acceptance criteria", Status: "pending", Verification: "checklist green"},
				},
			},
		},
	}
	if j.Action == "run-followup-planning" {
		existing, _ := store.GetPlan(j.ProjectID, j.SpecID)
		if len(existing.Phases) > 0 {
			next := len(existing.Phases) + 1
			existing.Phases = append(existing.Phases, PlanPhase{
				Phase: next, Name: "Follow-up", Type: "coding", ParallelSafe: false,
				Subtasks: []PlanSubtask{
					{ID: fmt.Sprintf("%d-0", next), Description: "Address follow-up request", Status: "pending"},
				},
			})
			existing.PlanStatus = "ready"
			existing.Status = "ready"
			plan = existing
		}
	}
	if err := store.PutPlan(j.ProjectID, j.SpecID, plan); err != nil {
		return "Failed to write implementation_plan.json", err
	}

	total, done := countPlanSubtasks(plan)
	prog := TaskProgress{
		IsRunning:        false,
		Action:           j.Action,
		Progress:         pct(done, total),
		SubtaskCompleted: done,
		SubtaskTotal:     total,
		CurrentPhaseName: "Design",
		RunID:            j.RunID,
	}
	completedAt := nowUTC()
	prog.CompletedAt = &completedAt
	_ = store.PutProgress(j.ProjectID, j.SpecID, prog)
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "planning", fmt.Sprintf("[%s] builtin planning wrote spec.md + plan (%d subtasks)\n", j.RunID, total))

	toStatus := "queue"
	if task.RequireReviewBeforeCoding {
		toStatus = "human_review"
	}
	if _, err := store.MoveTask(j.ProjectID, j.SpecID, toStatus); err != nil {
		return "Plan written but move failed", err
	}
	if toStatus == "human_review" {
		return "Planning complete (builtin): wrote spec.md + implementation plan; moved to human_review (require review before coding).", nil
	}
	return "Planning complete (builtin): wrote spec.md + implementation plan; moved to queue.", nil
}

func builtinImplementation(store *Store, j Job) (string, error) {
	if j.SpecID == "" {
		return "run-implementation requires specId", fmt.Errorf("specId required")
	}
	task, err := store.GetTask(j.ProjectID, j.SpecID)
	if err != nil {
		return "Task not found", err
	}
	if task.RequireReviewBeforeCoding {
		approved := false
		_ = store.withProject(j.ProjectID, func(p Project) error {
			var st map[string]interface{}
			path := filepath.Join(store.projectDir(p), "specs", j.SpecID, "review_state.json")
			if err := store.readJSON(path, &st); err != nil {
				return nil
			}
			if v, ok := st["approved"].(bool); ok {
				approved = v
			}
			return nil
		})
		if !approved && task.Status == "human_review" {
			return "Blocked: approve-for-coding required before implementation", fmt.Errorf("not approved")
		}
	}

	plan, err := store.GetPlan(j.ProjectID, j.SpecID)
	if err != nil || len(plan.Phases) == 0 {
		return "No plan — run planning first", fmt.Errorf("plan missing")
	}

	_, _ = store.MoveTask(j.ProjectID, j.SpecID, "in_progress")

	completedID := ""
	for i := range plan.Phases {
		for k := range plan.Phases[i].Subtasks {
			st := &plan.Phases[i].Subtasks[k]
			if st.Status == "pending" || st.Status == "" || st.Status == "in_progress" {
				st.Status = "completed"
				completedID = st.ID
				goto doneOne
			}
		}
	}
doneOne:
	if completedID == "" {
		_, _ = store.MoveTask(j.ProjectID, j.SpecID, "review")
		return "All subtasks already completed; moved to review.", nil
	}
	plan.Status = "in_progress"
	plan.PlanStatus = "in_progress"
	if err := store.PutPlan(j.ProjectID, j.SpecID, plan); err != nil {
		return "Failed to update plan", err
	}
	total, done := countPlanSubtasks(plan)
	prog := TaskProgress{
		IsRunning:        false,
		Action:           j.Action,
		Progress:         pct(done, total),
		SubtaskCompleted: done,
		SubtaskTotal:     total,
		RunID:            j.RunID,
	}
	if done >= total {
		prog.CurrentPhaseName = "Complete"
		_, _ = store.MoveTask(j.ProjectID, j.SpecID, "review")
	} else {
		prog.CurrentPhaseName = "Implement"
	}
	_ = store.PutProgress(j.ProjectID, j.SpecID, prog)
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation", fmt.Sprintf("[%s] completed subtask %s (%d/%d)\n", j.RunID, completedID, done, total))

	notePath := ""
	_ = store.withProject(j.ProjectID, func(p Project) error {
		notePath = filepath.Join(store.projectDir(p), "specs", j.SpecID, "IMPLEMENTATION_NOTES.md")
		prev, _ := os.ReadFile(notePath)
		line := fmt.Sprintf("- %s: completed subtask %s (builtin runner)\n", nowUTC().Format(time.RFC3339), completedID)
		return os.WriteFile(notePath, append(prev, []byte(line)...), 0o644)
	})

	if done >= total {
		return fmt.Sprintf("Implementation complete (builtin): finished subtask %s; all %d subtasks done; moved to review.", completedID, total), nil
	}
	return fmt.Sprintf("Implementation step (builtin): completed subtask %s (%d/%d). Re-enqueue to continue.", completedID, done, total), nil
}

func builtinReview(store *Store, j Job) (string, error) {
	if j.SpecID == "" {
		return "run-review requires specId", fmt.Errorf("specId required")
	}
	plan, err := store.GetPlan(j.ProjectID, j.SpecID)
	if err != nil {
		return "Plan missing", err
	}
	total, done := countPlanSubtasks(plan)
	pass := total > 0 && done >= total
	result := "FAIL"
	if pass {
		result = "PASS"
	}
	review := fmt.Sprintf("# Review result\n\n- runId: %s\n- result: %s\n- subtasks: %d/%d completed\n\n", j.RunID, result, done, total)
	if !pass {
		review += "## Findings\n\n- Incomplete subtasks remain — run implementation until plan is complete, then re-review.\n"
		_ = store.PutSpecFile(j.ProjectID, j.SpecID, "QA_FIX_REQUEST.md", review+"\nPlease complete remaining pending subtasks.\n")
		_, _ = store.MoveTask(j.ProjectID, j.SpecID, "in_progress")
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation", fmt.Sprintf("[%s] review FAIL\n", j.RunID))
		return "Review FAIL (builtin): incomplete plan; wrote QA_FIX_REQUEST.md; moved back to in_progress.", nil
	}
	_ = store.PutSpecFile(j.ProjectID, j.SpecID, "REVIEW.md", review)
	// Mark review-phase subtasks complete
	for i := range plan.Phases {
		if plan.Phases[i].Type == "review" {
			for k := range plan.Phases[i].Subtasks {
				plan.Phases[i].Subtasks[k].Status = "completed"
			}
		}
	}
	plan.Status = "reviewed"
	plan.PlanStatus = "reviewed"
	_ = store.PutPlan(j.ProjectID, j.SpecID, plan)
	total, done = countPlanSubtasks(plan)
	_ = store.PutProgress(j.ProjectID, j.SpecID, TaskProgress{
		Progress: pct(done, total), SubtaskCompleted: done, SubtaskTotal: total, RunID: j.RunID, CurrentPhaseName: "Review",
	})
	_, _ = store.MoveTask(j.ProjectID, j.SpecID, "human_review")
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation", fmt.Sprintf("[%s] review PASS → human_review\n", j.RunID))
	return "Review PASS (builtin): wrote REVIEW.md; moved to human_review.", nil
}

func builtinQaFix(store *Store, j Job) (string, error) {
	if j.SpecID == "" {
		return "run-qa-fix requires specId", fmt.Errorf("specId required")
	}
	_ = store.PutSpecFile(j.ProjectID, j.SpecID, "QA_FIX_REQUEST.md", "# QA fix applied\n\nBuiltin runner cleared pending QA findings. Re-run review.\n")
	plan, _ := store.GetPlan(j.ProjectID, j.SpecID)
	for i := range plan.Phases {
		for k := range plan.Phases[i].Subtasks {
			if plan.Phases[i].Subtasks[k].Status == "failed" || plan.Phases[i].Subtasks[k].Status == "stuck" {
				plan.Phases[i].Subtasks[k].Status = "pending"
			}
		}
	}
	_ = store.PutPlan(j.ProjectID, j.SpecID, plan)
	_, _ = store.MoveTask(j.ProjectID, j.SpecID, "in_progress")
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation", fmt.Sprintf("[%s] qa-fix applied\n", j.RunID))
	return "QA fix (builtin): reset failed subtasks; moved to in_progress. Re-run implementation/review.", nil
}

func builtinChangelog(store *Store, j Job) (string, error) {
	board, err := store.GetBoard(j.ProjectID)
	if err != nil {
		return "Board missing", err
	}
	doneIDs := board["done"]
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString(fmt.Sprintf("Generated %s by OPM builtin runner (`%s`).\n\n", nowUTC().Format(time.RFC3339), j.RunID))
	b.WriteString("### Added\n\n")
	if len(doneIDs) == 0 {
		b.WriteString("- _(no done tasks yet)_\n")
	} else {
		for _, id := range doneIDs {
			t, err := store.GetTask(j.ProjectID, id)
			title := id
			if err == nil {
				title = t.Title
			}
			b.WriteString(fmt.Sprintf("- **%s** (`%s`)", title, id))
			if err == nil && t.Description != "" {
				b.WriteString(" — " + truncateRunes(t.Description, 120))
			}
			b.WriteString("\n")
		}
	}
	b.WriteString("\n### Changed\n\n- _(none)_\n\n### Fixed\n\n- _(none)_\n")
	if err := store.PutChangelog(j.ProjectID, b.String()); err != nil {
		return "Failed to write changelog.md", err
	}
	return fmt.Sprintf("Changelog generated (builtin) from %d done task(s).", len(doneIDs)), nil
}

func builtinMetaNote(store *Store, j Job) (string, error) {
	_ = store.AppendProjectLog(j.ProjectID, j.Action, fmt.Sprintf("[%s] %s acknowledged (builtin placeholder — agent prompts not wired yet)\n", j.RunID, j.Action))
	return fmt.Sprintf("%s recorded (builtin placeholder). Roadmap/ideation agents need runner prompts next.", j.Action), nil
}

func countPlanSubtasks(plan ImplementationPlan) (total, done int) {
	for _, ph := range plan.Phases {
		for _, st := range ph.Subtasks {
			total++
			if st.Status == "completed" || st.Status == "done" {
				done++
			}
		}
	}
	return total, done
}

func pct(done, total int) int {
	if total <= 0 {
		return 0
	}
	return (done * 100) / total
}

func truncateRunes(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}
