package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// applyRunnerResult persists model output into plan/progress/logs.
// Returns (handled, message, err). handled=false means caller should run builtin helpers.
func applyRunnerResult(store *Store, j Job, rr RunnerResult, taskWorkDir string) (bool, string, error) {
	if rr.Mode != "model" {
		return false, "", nil
	}
	switch j.Action {
	case "run-planning", "run-followup-planning":
		msg, err := applyModelPlanning(store, j, rr)
		return true, msg, err
	case "run-implementation":
		msg, err := applyModelImplementation(store, j, rr, taskWorkDir)
		return true, msg, err
	case "run-review":
		msg, err := applyModelReview(store, j, rr)
		return true, msg, err
	case "run-qa-fix":
		msg, err := applyModelQaFix(store, j, rr, taskWorkDir)
		return true, msg, err
	case "run-ideation":
		if len(rr.Ideas) == 0 {
			return false, "", nil
		}
		msg, err := applyModelIdeation(store, j, rr)
		return true, msg, err
	case "run-roadmap-discovery":
		if strings.TrimSpace(rr.Vision) == "" && len(rr.Phases) == 0 && rr.DiscoveryBlob == nil {
			return false, "", nil
		}
		msg, err := applyModelRoadmapDiscovery(store, j, rr)
		return true, msg, err
	case "run-roadmap-competitor":
		if len(rr.Competitor) == 0 {
			return false, "", nil
		}
		msg, err := applyModelRoadmapCompetitor(store, j, rr)
		return true, msg, err
	case "run-roadmap-features":
		if len(rr.Features) == 0 && strings.TrimSpace(rr.Vision) == "" && len(rr.Phases) == 0 {
			return false, "", nil
		}
		msg, err := applyModelRoadmapFeatures(store, j, rr)
		if err != nil && strings.Contains(err.Error(), "phases missing") {
			return false, "", nil
		}
		return true, msg, err
	default:
		return false, "", nil
	}
}

func applyModelPlanning(store *Store, j Job, rr RunnerResult) (string, error) {
	if j.SpecID == "" {
		return "run-planning requires specId", fmt.Errorf("specId required")
	}
	task, err := store.GetTask(j.ProjectID, j.SpecID)
	if err != nil {
		return "Task not found", err
	}

	spec := strings.TrimSpace(rr.SpecMarkdown)
	if spec == "" {
		spec = fmt.Sprintf("# %s\n\n## Summary\n\n%s\n\n## Notes\n\nGenerated by OPM model runner (%s, model=%s).\n",
			task.Title, nz(task.Description, "_No description provided._"), j.RunID, nz(rr.Model, "unknown"))
		if rr.RawExcerpt != "" {
			spec += "\n## Model excerpt\n\n" + rr.RawExcerpt + "\n"
		}
	}
	if err := store.PutSpecMarkdown(j.ProjectID, j.SpecID, spec); err != nil {
		return "Failed to write spec.md", err
	}

	var plan ImplementationPlan
	if rr.Plan != nil && len(rr.Plan.Phases) > 0 {
		plan = *rr.Plan
	} else {
		plan = ImplementationPlan{
			Feature: task.Title, WorkflowType: "feature", ServicesInvolved: []string{"opm-api"},
			SpecFile: "spec.md", Status: "ready", PlanStatus: "ready",
			FinalAcceptance: []string{"Behavior matches spec summary"},
			Phases: []PlanPhase{
				{Phase: 1, Name: "Design", Type: "planning", Subtasks: []PlanSubtask{
					{ID: "1-0", Description: "Confirm scope", Status: "completed", Verification: "spec.md"},
				}},
				{Phase: 2, Name: "Implement", Type: "coding", DependsOn: []int{1}, Subtasks: []PlanSubtask{
					{ID: "2-0", Description: "Implement: " + task.Title, Status: "pending"},
				}},
				{Phase: 3, Name: "Review", Type: "review", DependsOn: []int{2}, Subtasks: []PlanSubtask{
					{ID: "3-0", Description: "Self-review", Status: "pending"},
				}},
			},
		}
	}
	if plan.Feature == "" {
		plan.Feature = task.Title
	}
	if plan.Status == "" {
		plan.Status = "ready"
	}
	if plan.PlanStatus == "" {
		plan.PlanStatus = "ready"
	}
	if err := store.PutPlan(j.ProjectID, j.SpecID, plan); err != nil {
		return "Failed to write implementation_plan.json", err
	}

	total, done := countPlanSubtasks(plan)
	completedAt := nowUTC()
	_ = store.PutProgress(j.ProjectID, j.SpecID, TaskProgress{
		IsRunning: false, Action: j.Action, Progress: pct(done, total),
		SubtaskCompleted: done, SubtaskTotal: total, CurrentPhaseName: "Design",
		RunID: j.RunID, CompletedAt: &completedAt,
	})
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "planning",
		fmt.Sprintf("[%s] model planning (%s) wrote spec.md + plan (%d subtasks)\n", j.RunID, nz(rr.Model, "?"), total))
	if rr.RawExcerpt != "" {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "planning",
			fmt.Sprintf("[%s] model excerpt: %s\n", j.RunID, truncateRunes(rr.RawExcerpt, 400)))
	}

	toStatus := "queue"
	if task.RequireReviewBeforeCoding {
		toStatus = "human_review"
	}
	if _, err := store.MoveTask(j.ProjectID, j.SpecID, toStatus); err != nil {
		return "Plan written but move failed", err
	}
	return fmt.Sprintf("Planning complete (model/%s): wrote spec.md + plan; moved to %s.", nz(rr.Model, "model"), toStatus), nil
}

func applyModelImplementation(store *Store, j Job, rr RunnerResult, taskWorkDir string) (string, error) {
	return applyModelImplementationOpts(store, j, rr, taskWorkDir, false)
}

func applyModelImplementationOpts(store *Store, j Job, rr RunnerResult, taskWorkDir string, keepRunning bool) (string, error) {
	msg, err := builtinImplementationOpts(store, j, keepRunning)
	if err != nil {
		return msg, err
	}
	note := strings.TrimSpace(rr.ImplementationNotes)
	if note == "" && rr.RawExcerpt != "" {
		note = rr.RawExcerpt
	}
	if note != "" {
		_ = store.withProject(j.ProjectID, func(p Project) error {
			notePath := filepath.Join(store.projectDir(p), "specs", j.SpecID, "IMPLEMENTATION_NOTES.md")
			prev, _ := os.ReadFile(notePath)
			line := fmt.Sprintf("\n### Runner notes (%s, %s)\n\n%s\n",
				nowUTC().Format(time.RFC3339), nz(rr.Model, "model"), note)
			return os.WriteFile(notePath, append(prev, []byte(line)...), 0o644)
		})
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] runner implementation notes (%s): %s\n", j.RunID, nz(rr.Model, "?"), truncateRunes(note, 400)))
	}
	msg = strings.Replace(msg, "(builtin)", "(model/"+nz(rr.Model, "model")+")", 1)
	if !strings.Contains(msg, "model/") {
		msg = "Model enrichment applied. " + msg
	}
	msg = strings.Replace(msg, "Re-enqueue to continue.", "", 1)
	msg = strings.Replace(msg, builtinNoCodeNotice, "", 1)
	return strings.TrimSpace(msg) + " " + recordImplementationChangeSet(store, j, rr, taskWorkDir), nil
}

// recordImplementationChangeSet persists the runner's file changes so `deliver`
// can commit them, and returns the operator-facing sentence about what was
// actually produced. It never claims code was written when it was not.
func recordImplementationChangeSet(store *Store, j Job, rr RunnerResult, taskWorkDir string) string {
	if j.SpecID == "" {
		return ""
	}
	cs := changeSetFromRunner(j.RunID, rr)
	if len(cs.Files) == 0 {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] no source changes produced — nothing to deliver (%s)\n",
				j.RunID, nz(cs.Note, "runner returned no files")))
		return "No source changes were produced this step."
	}
	if taskWorkDir != "" && !workspaceIsStub(taskWorkDir) {
		applied, aerr := applyChangeSet(taskWorkDir, cs, deliveryLimits())
		if aerr != nil {
			_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
				fmt.Sprintf("[%s] failed to apply %d file change(s) to session workspace: %v\n", j.RunID, len(cs.Files), aerr))
			return fmt.Sprintf("Produced %d file change(s) but applying to the session workspace failed: %v.", len(cs.Files), aerr)
		}
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] applied %d file change(s) to session workspace: %s\n",
				j.RunID, len(applied.Applied), strings.Join(applied.Applied, ", ")))
	}
	if err := store.PutChangeSetMerged(j.ProjectID, j.SpecID, cs); err != nil {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] failed to record %d file change(s): %v\n", j.RunID, len(cs.Files), err))
		return fmt.Sprintf("Produced %d file change(s) but recording them failed: %v.", len(cs.Files), err)
	}
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
		fmt.Sprintf("[%s] merged %d file change(s) into session change set: %s\n",
			j.RunID, len(cs.Files), strings.Join(cs.paths(), ", ")))
	return fmt.Sprintf("Applied %d file change(s) to the shared implementation workspace.", len(cs.Files))
}

func applyModelReview(store *Store, j Job, rr RunnerResult) (string, error) {
	if j.SpecID == "" {
		return "run-review requires specId", fmt.Errorf("specId required")
	}
	plan, err := store.GetPlan(j.ProjectID, j.SpecID)
	if err != nil {
		return "Plan missing", err
	}
	total, done := countPlanSubtasks(plan)
	planComplete := total > 0 && done >= total

	pass := planComplete
	if rr.ReviewPass != nil {
		pass = *rr.ReviewPass && planComplete
	}

	review := strings.TrimSpace(rr.ReviewMarkdown)
	if review == "" {
		result := "FAIL"
		if pass {
			result = "PASS"
		}
		review = fmt.Sprintf("# Review result\n\n- runId: %s\n- result: %s\n- model: %s\n- subtasks: %d/%d\n\n",
			j.RunID, result, nz(rr.Model, "unknown"), done, total)
		if rr.RawExcerpt != "" {
			review += "## Model excerpt\n\n" + rr.RawExcerpt + "\n"
		}
	}

	if !pass {
		_ = store.PutSpecFile(j.ProjectID, j.SpecID, "QA_FIX_REQUEST.md", review+"\n\nPlease address findings and re-run review.\n")
		_, _ = store.MoveTask(j.ProjectID, j.SpecID, "in_progress")
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation",
			fmt.Sprintf("[%s] model review FAIL (%s)\n", j.RunID, nz(rr.Model, "?")))
		return fmt.Sprintf("Review FAIL (model/%s): wrote QA_FIX_REQUEST.md; moved to in_progress.", nz(rr.Model, "model")), nil
	}

	_ = store.PutSpecFile(j.ProjectID, j.SpecID, "REVIEW.md", review)
	for i := range plan.Phases {
		if plan.Phases[i].Type == "review" {
			for k := range plan.Phases[i].Subtasks {
				plan.Phases[i].Subtasks[k].Status = "completed"
			}
		}
	}
	plan.Status = "reviewed"
	plan.PlanStatus = "reviewed"
	_ = store.PutPlan(j.ProjectID, j.SpecID, plan)
	total, done = countPlanSubtasks(plan)
	_ = store.PutProgress(j.ProjectID, j.SpecID, TaskProgress{
		Progress: pct(done, total), SubtaskCompleted: done, SubtaskTotal: total, RunID: j.RunID, CurrentPhaseName: "Review",
	})
	task, _ := store.GetTask(j.ProjectID, j.SpecID)
	toStatus := reviewPassStatus(task)
	_, _ = store.MoveTask(j.ProjectID, j.SpecID, toStatus)
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation",
		fmt.Sprintf("[%s] model review PASS (%s) → %s\n", j.RunID, nz(rr.Model, "?"), toStatus))
	return fmt.Sprintf("Review PASS (model/%s): wrote REVIEW.md; moved to %s.", nz(rr.Model, "model"), toStatus), nil
}

func applyModelQaFix(store *Store, j Job, rr RunnerResult, taskWorkDir string) (string, error) {
	msg, err := builtinQaFix(store, j)
	if err != nil {
		return msg, err
	}
	msg = strings.Replace(msg, "(builtin)", "(model/"+nz(rr.Model, "model")+")", 1)
	return strings.TrimSpace(msg) + " " + recordImplementationChangeSet(store, j, rr, taskWorkDir), nil
}

func applyModelIdeation(store *Store, j Job, rr RunnerResult) (string, error) {
	if len(rr.Ideas) == 0 {
		return "model ideation returned no ideas", fmt.Errorf("ideas missing")
	}
	existing, _ := store.GetIdeation(j.ProjectID)
	if existing == nil {
		existing = emptyIdeation()
	}

	implIDs, implTitles := implementedIdeationFromDone(store, j.ProjectID, j.IdeationType)

	added := 0
	skippedImplemented := 0
	now := nowUTC().Format(time.RFC3339)
	for typ, incoming := range rr.Ideas {
		typ = strings.TrimSpace(typ)
		if !containsString(IdeationTypes, typ) {
			continue
		}
		if j.IdeationType != "" && typ != j.IdeationType {
			continue
		}
		bucket := existing[typ]
		if bucket == nil {
			bucket = []Idea{}
		}
		have := map[string]bool{}
		for _, idea := range bucket {
			have[strings.ToLower(strings.TrimSpace(idea.Title))] = true
		}
		for _, idea := range incoming {
			title := strings.TrimSpace(idea.Title)
			if title == "" || have[strings.ToLower(title)] {
				continue
			}
			id := strings.TrimSpace(idea.ID)
			if id != "" && implIDs[id] {
				skippedImplemented++
				continue
			}
			if implTitles[normalizeTitle(title)] {
				skippedImplemented++
				continue
			}
			if id == "" {
				id = shortID("idea")
			}
			status := strings.TrimSpace(idea.Status)
			if status == "" {
				status = "open"
			}
			created := strings.TrimSpace(idea.CreatedAt)
			if created == "" {
				created = now
			}
			desc := strings.TrimSpace(idea.Description)
			rationale := strings.TrimSpace(idea.Rationale)
			// Fold type-specific extras that models may emit without store fields.
			desc, rationale = foldIdeaExtras(desc, rationale, idea)
			bucket = append(bucket, Idea{
				ID:                     id,
				Type:                   typ,
				Title:                  title,
				Description:            desc,
				Rationale:              nz(rationale, "Generated by OPM model ideation ("+nz(rr.Model, "auto")+")."),
				EstimatedEffort:        strings.TrimSpace(idea.EstimatedEffort),
				AffectedFiles:          idea.AffectedFiles,
				ImplementationApproach: strings.TrimSpace(idea.ImplementationApproach),
				Status:                 status,
				CreatedAt:              created,
			})
			have[strings.ToLower(title)] = true
			added++
		}
		existing[typ] = bucket
	}

	types := IdeationTypes
	if t := strings.TrimSpace(j.IdeationType); t != "" {
		types = []string{t}
	}
	if added == 0 {
		msg := fmt.Sprintf("Ideation (model/%s): added 0 idea(s) across %d type(s) (duplicates, implemented, or empty).",
			nz(rr.Model, "model"), len(types))
		if skippedImplemented > 0 {
			msg += fmt.Sprintf(" Skipped %d already-implemented.", skippedImplemented)
		}
		return msg, nil
	}
	if err := store.PutIdeation(j.ProjectID, existing); err != nil {
		return "Failed to write ideation.json", err
	}
	_ = store.AppendProjectLog(j.ProjectID, "run-ideation",
		fmt.Sprintf("[%s] ideation agent added %d idea(s) types=%v (model/%s; skipped_implemented=%d)\n",
			j.RunID, added, types, nz(rr.Model, "?"), skippedImplemented))
	return fmt.Sprintf("Ideation (model/%s): added %d idea(s) across %d type(s).", nz(rr.Model, "model"), added, len(types)), nil
}

// foldIdeaExtras merges severity/CWE-style extras into description/rationale when present
// via JSON round-trip fields that Idea does not store directly.
func foldIdeaExtras(desc, rationale string, idea Idea) (string, string) {
	// Idea struct has no Severity/CWE; extras already in Description/Rationale from normalize.
	_ = idea
	return desc, rationale
}

func applyModelRoadmapDiscovery(store *Store, j Job, rr RunnerResult) (string, error) {
	p, err := store.GetProject(j.ProjectID)
	if err != nil {
		return "Project not found", err
	}
	rm, _ := store.GetRoadmap(j.ProjectID)
	name := nz(p.Name, p.OwnerRepo)
	if rm.ID == "" {
		rm.ID = "roadmap-1"
	}
	if rm.ProjectName == "" {
		rm.ProjectName = name
	}
	if rm.Version == "" {
		rm.Version = "0.1.0"
	}

	vision := strings.TrimSpace(rr.Vision)
	if vision == "" && rr.DiscoveryBlob != nil {
		if pv, ok := rr.DiscoveryBlob["product_vision"].(map[string]any); ok {
			if ol, ok := pv["one_liner"].(string); ok {
				vision = strings.TrimSpace(ol)
			}
		}
	}
	if vision != "" {
		rm.Vision = vision
	}

	audience := strings.TrimSpace(rr.TargetAudience)
	if audience == "" && rr.DiscoveryBlob != nil {
		audience = compactAudience(rr.DiscoveryBlob["target_audience"])
	}
	if audience != "" {
		rm.TargetAudience = audience
	}

	if len(rr.Phases) > 0 {
		rm.Phases = mergeRoadmapPhases(rm.Phases, rr.Phases)
	}

	if rm.Metadata == nil {
		rm.Metadata = map[string]any{}
	}
	rm.Metadata["last_discovery_run"] = j.RunID
	rm.Metadata["discovered_at"] = nowUTC().Format(time.RFC3339)
	rm.Metadata["discovery_source"] = "model/" + nz(rr.Model, "model")
	if rr.DiscoveryBlob != nil {
		rm.Metadata["discovery"] = rr.DiscoveryBlob
	}

	if err := store.PutRoadmap(j.ProjectID, rm); err != nil {
		return "Failed to write roadmap.json", err
	}
	_ = store.AppendProjectLog(j.ProjectID, "run-roadmap-discovery",
		fmt.Sprintf("[%s] discovery wrote vision + %d phase(s) (model/%s)\n", j.RunID, len(rm.Phases), nz(rr.Model, "?")))
	return fmt.Sprintf("Roadmap discovery (model/%s): vision set; %d phase(s).", nz(rr.Model, "model"), len(rm.Phases)), nil
}

func applyModelRoadmapFeatures(store *Store, j Job, rr RunnerResult) (string, error) {
	rm, err := store.GetRoadmap(j.ProjectID)
	if err != nil {
		rm = Roadmap{}
	}
	// Only bootstrap discovery from the features result when phases are still empty
	// (OPM convenience vs hard-fail). Do not let a features hallucination rewrite
	// an existing discovery vision/phases.
	if len(rm.Phases) == 0 && (len(rr.Phases) > 0 || strings.TrimSpace(rr.Vision) != "" || rr.DiscoveryBlob != nil) {
		if _, err := applyModelRoadmapDiscovery(store, j, rr); err != nil {
			return "Discovery bootstrap failed", err
		}
		rm, err = store.GetRoadmap(j.ProjectID)
		if err != nil {
			return "Roadmap missing", err
		}
	}
	if len(rm.Phases) == 0 {
		// Still empty after optional discovery — fall through to builtin.
		return "", fmt.Errorf("phases missing after model features")
	}

	existing := map[string]bool{}
	implemented := map[string]bool{}
	for _, f := range rm.Features {
		key := strings.ToLower(strings.TrimSpace(f.Title))
		existing[key] = true
		if featureStatusImplemented(f.Status) {
			implemented[key] = true
		}
	}

	phaseIDs := map[string]bool{}
	phaseByName := map[string]string{}
	for _, ph := range rm.Phases {
		phaseIDs[ph.ID] = true
		phaseByName[strings.ToLower(strings.TrimSpace(ph.Name))] = ph.ID
	}

	added := 0
	skipped := 0
	for _, feat := range rr.Features {
		title := strings.TrimSpace(feat.Title)
		if title == "" {
			continue
		}
		key := strings.ToLower(title)
		if existing[key] || implemented[key] {
			skipped++
			continue
		}
		fid := strings.TrimSpace(feat.ID)
		if fid == "" {
			fid = shortID("feat")
		}
		phaseID := strings.TrimSpace(feat.PhaseID)
		if phaseID != "" && !phaseIDs[phaseID] {
			// Try name match, else first phase.
			if alt, ok := phaseByName[strings.ToLower(phaseID)]; ok {
				phaseID = alt
			} else {
				phaseID = rm.Phases[0].ID
			}
		}
		if phaseID == "" {
			phaseID = rm.Phases[0].ID
		}
		status := strings.TrimSpace(feat.Status)
		if status == "" {
			status = "planned"
		}
		priority := strings.TrimSpace(feat.Priority)
		if priority == "" {
			priority = "should"
		}
		newFeat := RoadmapFeature{
			ID:                 fid,
			Title:              title,
			Description:        strings.TrimSpace(feat.Description),
			Rationale:          nz(strings.TrimSpace(feat.Rationale), "Generated by OPM model roadmap features ("+nz(rr.Model, "auto")+")."),
			Priority:           priority,
			Complexity:         strings.TrimSpace(feat.Complexity),
			Impact:             strings.TrimSpace(feat.Impact),
			PhaseID:            phaseID,
			Dependencies:       feat.Dependencies,
			Status:             status,
			AcceptanceCriteria: feat.AcceptanceCriteria,
			UserStories:        feat.UserStories,
		}
		rm.Features = append(rm.Features, newFeat)
		for i := range rm.Phases {
			if rm.Phases[i].ID == phaseID {
				rm.Phases[i].Features = append(rm.Phases[i].Features, fid)
				break
			}
		}
		existing[key] = true
		added++
	}

	if rm.Metadata == nil {
		rm.Metadata = map[string]any{}
	}
	rm.Metadata["last_features_run"] = j.RunID
	rm.Metadata["features_source"] = "model/" + nz(rr.Model, "model")

	if added == 0 {
		return fmt.Sprintf("Roadmap features (model/%s): added 0 (duplicates/implemented=%d).", nz(rr.Model, "model"), skipped), nil
	}
	// ORA's schema check, applied here rather than at publish time only. A
	// validation failure does NOT discard the features: they are real model output,
	// and throwing them away loses work over a fixable structural problem. It is
	// recorded on the roadmap and surfaced in the message so the board shows the
	// caveat, and roadmap publishing refuses until it is resolved.
	if verr := validateRoadmapJSON(rm); verr != nil {
		if rm.Metadata == nil {
			rm.Metadata = map[string]any{}
		}
		rm.Metadata["validation_error"] = verr.Error()
	} else if rm.Metadata != nil {
		delete(rm.Metadata, "validation_error")
	}
	if err := store.PutRoadmap(j.ProjectID, rm); err != nil {
		return "Failed to write roadmap features", err
	}
	_ = store.AppendProjectLog(j.ProjectID, "run-roadmap-features",
		fmt.Sprintf("[%s] features agent added %d feature(s) (model/%s; skipped=%d)\n",
			j.RunID, added, nz(rr.Model, "?"), skipped))
	msg := fmt.Sprintf("Roadmap features (model/%s): added %d feature(s) across %d phase(s).",
		nz(rr.Model, "model"), added, len(rm.Phases))
	if verr := validateRoadmapJSON(rm); verr != nil {
		msg += " Not publishable yet: " + verr.Error()
	}
	return msg, nil
}

// mergeRoadmapPhases updates/adds phases by matching name (case-insensitive),
// preserving milestone binds and IDs on existing phases. When no existing phase
// has a GitHub milestone bind, prefer the incoming set (still reuse IDs by name)
// so re-runs do not accumulate unbounded orphan phases.
func mergeRoadmapPhases(existing, incoming []RoadmapPhase) []RoadmapPhase {
	if len(incoming) == 0 {
		return existing
	}
	hasBind := false
	byName := map[string]RoadmapPhase{}
	for _, ph := range existing {
		byName[strings.ToLower(strings.TrimSpace(ph.Name))] = ph
		if ph.GithubMilestoneNumber > 0 {
			hasBind = true
		}
	}

	if !hasBind {
		out := make([]RoadmapPhase, 0, len(incoming))
		seen := map[string]bool{}
		for i, ph := range incoming {
			name := strings.TrimSpace(ph.Name)
			if name == "" {
				continue
			}
			key := strings.ToLower(name)
			if seen[key] {
				continue
			}
			seen[key] = true
			id := strings.TrimSpace(ph.ID)
			status := strings.TrimSpace(ph.Status)
			if status == "" {
				status = "planned"
			}
			order := ph.Order
			if order == 0 {
				order = i + 1
			}
			prev, ok := byName[key]
			if ok {
				if id == "" {
					id = prev.ID
				}
			}
			if id == "" {
				id = shortID("phase")
			}
			out = append(out, RoadmapPhase{
				ID: id, Name: name, Description: strings.TrimSpace(ph.Description),
				Order: order, Status: status, Features: []string{},
			})
		}
		if len(out) > 0 {
			return out
		}
	}

	out := append([]RoadmapPhase{}, existing...)
	idxByName := map[string]int{}
	for i, ph := range out {
		idxByName[strings.ToLower(strings.TrimSpace(ph.Name))] = i
	}
	for _, ph := range incoming {
		name := strings.TrimSpace(ph.Name)
		if name == "" {
			continue
		}
		key := strings.ToLower(name)
		if i, ok := idxByName[key]; ok {
			if d := strings.TrimSpace(ph.Description); d != "" {
				out[i].Description = d
			}
			if ph.Order > 0 {
				out[i].Order = ph.Order
			}
			if s := strings.TrimSpace(ph.Status); s != "" {
				out[i].Status = s
			}
			continue
		}
		id := strings.TrimSpace(ph.ID)
		if id == "" {
			id = shortID("phase")
		}
		status := strings.TrimSpace(ph.Status)
		if status == "" {
			status = "planned"
		}
		order := ph.Order
		if order == 0 {
			order = len(out) + 1
		}
		out = append(out, RoadmapPhase{
			ID: id, Name: name, Description: strings.TrimSpace(ph.Description),
			Order: order, Status: status, Features: []string{},
		})
		idxByName[key] = len(out) - 1
	}
	return out
}

func compactAudience(v any) string {
	switch t := v.(type) {
	case string:
		return strings.TrimSpace(t)
	case map[string]any:
		parts := []string{}
		if p, ok := t["primary_persona"].(string); ok && strings.TrimSpace(p) != "" {
			parts = append(parts, strings.TrimSpace(p))
		} else if p, ok := t["primary"].(string); ok && strings.TrimSpace(p) != "" {
			parts = append(parts, strings.TrimSpace(p))
		}
		if u, ok := t["usage_context"].(string); ok && strings.TrimSpace(u) != "" {
			parts = append(parts, strings.TrimSpace(u))
		}
		return strings.Join(parts, " — ")
	default:
		return ""
	}
}

func containsString(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}

// applyModelRoadmapCompetitor stores a model-produced competitor analysis on the
// roadmap's metadata.
//
// It is metadata rather than a document of its own because the analysis is an
// input to discovery and features, not something the board renders. Storing it
// beside the roadmap also means it travels with the roadmap when that is exported.
func applyModelRoadmapCompetitor(store *Store, j Job, rr RunnerResult) (string, error) {
	rm, err := store.GetRoadmap(j.ProjectID)
	if err != nil {
		// Competitor analysis can legitimately be the first roadmap stage anyone
		// runs, so a missing document starts one rather than failing.
		rm = Roadmap{ID: "roadmap-1"}
	}
	name := rm.ProjectName
	if p, perr := store.GetProject(j.ProjectID); perr == nil {
		name = nz(name, p.Name)
	}
	analysis, fromModel := parseCompetitorAnalysis(rr.Competitor, name, j.Competitors)
	if err := storeCompetitorAnalysis(store, j.ProjectID, rm, analysis); err != nil {
		return "Failed to store competitor analysis", err
	}
	source := "model"
	if !fromModel {
		// Say which it was. A heuristic analysis presented as model output is the
		// kind of thing that gets quoted in a planning meeting.
		source = "heuristic fallback"
	}
	_ = store.AppendProjectLog(j.ProjectID, "run-roadmap-competitor",
		fmt.Sprintf("[%s] competitor analysis (%s): %d competitor(s), %d market gap(s)\n",
			j.RunID, source, len(analysis.Competitors), len(analysis.MarketGaps)))
	return fmt.Sprintf("Stored competitor analysis from %s: %d competitor(s), %d market gap(s), %d differentiator(s)",
		source, len(analysis.Competitors), len(analysis.MarketGaps), len(analysis.Differentiators)), nil
}
