package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// applyRunnerResult persists model output into plan/progress/logs.
// Returns (handled, message, err). handled=false means caller should run builtin helpers.
func applyRunnerResult(store *Store, j Job, rr RunnerResult) (bool, string, error) {
	if rr.Mode != "model" {
		return false, "", nil
	}
	switch j.Action {
	case "run-planning", "run-followup-planning":
		msg, err := applyModelPlanning(store, j, rr)
		return true, msg, err
	case "run-implementation":
		msg, err := applyModelImplementation(store, j, rr)
		return true, msg, err
	case "run-review":
		msg, err := applyModelReview(store, j, rr)
		return true, msg, err
	default:
		return false, "", nil
	}
}

func applyModelPlanning(store *Store, j Job, rr RunnerResult) (string, error) {
	if j.SpecID == "" {
		return "run-planning requires specId", fmt.Errorf("specId required")
	}
	task, err := store.GetTask(j.ProjectID, j.SpecID)
	if err != nil {
		return "Task not found", err
	}

	spec := strings.TrimSpace(rr.SpecMarkdown)
	if spec == "" {
		spec = fmt.Sprintf("# %s\n\n## Summary\n\n%s\n\n## Notes\n\nGenerated by OPM model runner (%s, model=%s).\n",
			task.Title, nz(task.Description, "_No description provided._"), j.RunID, nz(rr.Model, "unknown"))
		if rr.RawExcerpt != "" {
			spec += "\n## Model excerpt\n\n" + rr.RawExcerpt + "\n"
		}
	}
	if err := store.PutSpecMarkdown(j.ProjectID, j.SpecID, spec); err != nil {
		return "Failed to write spec.md", err
	}

	var plan ImplementationPlan
	if rr.Plan != nil && len(rr.Plan.Phases) > 0 {
		plan = *rr.Plan
	} else {
		plan = ImplementationPlan{
			Feature: task.Title, WorkflowType: "feature", ServicesInvolved: []string{"opm-api"},
			SpecFile: "spec.md", Status: "ready", PlanStatus: "ready",
			FinalAcceptance: []string{"Behavior matches spec summary"},
			Phases: []PlanPhase{
				{Phase: 1, Name: "Design", Type: "planning", Subtasks: []PlanSubtask{
					{ID: "1-0", Description: "Confirm scope", Status: "completed", Verification: "spec.md"},
				}},
				{Phase: 2, Name: "Implement", Type: "coding", DependsOn: []int{1}, Subtasks: []PlanSubtask{
					{ID: "2-0", Description: "Implement: " + task.Title, Status: "pending"},
				}},
				{Phase: 3, Name: "Review", Type: "review", DependsOn: []int{2}, Subtasks: []PlanSubtask{
					{ID: "3-0", Description: "Self-review", Status: "pending"},
				}},
			},
		}
	}
	if plan.Feature == "" {
		plan.Feature = task.Title
	}
	if plan.Status == "" {
		plan.Status = "ready"
	}
	if plan.PlanStatus == "" {
		plan.PlanStatus = "ready"
	}
	if err := store.PutPlan(j.ProjectID, j.SpecID, plan); err != nil {
		return "Failed to write implementation_plan.json", err
	}

	total, done := countPlanSubtasks(plan)
	completedAt := nowUTC()
	_ = store.PutProgress(j.ProjectID, j.SpecID, TaskProgress{
		IsRunning: false, Action: j.Action, Progress: pct(done, total),
		SubtaskCompleted: done, SubtaskTotal: total, CurrentPhaseName: "Design",
		RunID: j.RunID, CompletedAt: &completedAt,
	})
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "planning",
		fmt.Sprintf("[%s] model planning (%s) wrote spec.md + plan (%d subtasks)\n", j.RunID, nz(rr.Model, "?"), total))
	if rr.RawExcerpt != "" {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "planning",
			fmt.Sprintf("[%s] model excerpt: %s\n", j.RunID, truncateRunes(rr.RawExcerpt, 400)))
	}

	toStatus := "queue"
	if task.RequireReviewBeforeCoding {
		toStatus = "human_review"
	}
	if _, err := store.MoveTask(j.ProjectID, j.SpecID, toStatus); err != nil {
		return "Plan written but move failed", err
	}
	return fmt.Sprintf("Planning complete (model/%s): wrote spec.md + plan; moved to %s.", nz(rr.Model, "model"), toStatus), nil
}

func applyModelImplementation(store *Store, j Job, rr RunnerResult) (string, error) {
	msg, err := builtinImplementation(store, j)
	if err != nil {
		return msg, err
	}
	note := strings.TrimSpace(rr.ImplementationNotes)
	if note == "" && rr.RawExcerpt != "" {
		note = rr.RawExcerpt
	}
	if note != "" {
		_ = store.withProject(j.ProjectID, func(p Project) error {
			notePath := filepath.Join(store.projectDir(p), "specs", j.SpecID, "IMPLEMENTATION_NOTES.md")
			prev, _ := os.ReadFile(notePath)
			line := fmt.Sprintf("\n### Runner notes (%s, %s)\n\n%s\n",
				nowUTC().Format(time.RFC3339), nz(rr.Model, "model"), note)
			return os.WriteFile(notePath, append(prev, []byte(line)...), 0o644)
		})
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] runner implementation notes (%s): %s\n", j.RunID, nz(rr.Model, "?"), truncateRunes(note, 400)))
	}
	msg = strings.Replace(msg, "(builtin)", "(model/"+nz(rr.Model, "model")+")", 1)
	if !strings.Contains(msg, "model/") {
		msg = "Model enrichment applied. " + msg
	}
	return msg + " " + recordImplementationChangeSet(store, j, rr), nil
}

// recordImplementationChangeSet persists the runner's file changes so `deliver`
// can commit them, and returns the operator-facing sentence about what was
// actually produced. It never claims code was written when it was not.
func recordImplementationChangeSet(store *Store, j Job, rr RunnerResult) string {
	if j.SpecID == "" {
		return ""
	}
	cs := changeSetFromRunner(j.RunID, rr)
	if len(cs.Files) == 0 {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] no source changes produced — nothing to deliver (%s)\n",
				j.RunID, nz(cs.Note, "runner returned no files")))
		return "No source changes were produced, so there is nothing to deliver yet."
	}
	if err := store.PutChangeSet(j.ProjectID, j.SpecID, cs); err != nil {
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
			fmt.Sprintf("[%s] failed to record %d file change(s): %v\n", j.RunID, len(cs.Files), err))
		return fmt.Sprintf("Produced %d file change(s) but recording them failed: %v.", len(cs.Files), err)
	}
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "implementation",
		fmt.Sprintf("[%s] recorded %d file change(s) for delivery: %s\n",
			j.RunID, len(cs.Files), strings.Join(cs.paths(), ", ")))
	return fmt.Sprintf("Recorded %d file change(s) ready to deliver (POST …/deliver).", len(cs.Files))
}

func applyModelReview(store *Store, j Job, rr RunnerResult) (string, error) {
	if j.SpecID == "" {
		return "run-review requires specId", fmt.Errorf("specId required")
	}
	plan, err := store.GetPlan(j.ProjectID, j.SpecID)
	if err != nil {
		return "Plan missing", err
	}
	total, done := countPlanSubtasks(plan)
	planComplete := total > 0 && done >= total

	pass := planComplete
	if rr.ReviewPass != nil {
		pass = *rr.ReviewPass && planComplete
	}

	review := strings.TrimSpace(rr.ReviewMarkdown)
	if review == "" {
		result := "FAIL"
		if pass {
			result = "PASS"
		}
		review = fmt.Sprintf("# Review result\n\n- runId: %s\n- result: %s\n- model: %s\n- subtasks: %d/%d\n\n",
			j.RunID, result, nz(rr.Model, "unknown"), done, total)
		if rr.RawExcerpt != "" {
			review += "## Model excerpt\n\n" + rr.RawExcerpt + "\n"
		}
	}

	if !pass {
		_ = store.PutSpecFile(j.ProjectID, j.SpecID, "QA_FIX_REQUEST.md", review+"\n\nPlease address findings and re-run review.\n")
		_, _ = store.MoveTask(j.ProjectID, j.SpecID, "in_progress")
		_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation",
			fmt.Sprintf("[%s] model review FAIL (%s)\n", j.RunID, nz(rr.Model, "?")))
		return fmt.Sprintf("Review FAIL (model/%s): wrote QA_FIX_REQUEST.md; moved to in_progress.", nz(rr.Model, "model")), nil
	}

	_ = store.PutSpecFile(j.ProjectID, j.SpecID, "REVIEW.md", review)
	for i := range plan.Phases {
		if plan.Phases[i].Type == "review" {
			for k := range plan.Phases[i].Subtasks {
				plan.Phases[i].Subtasks[k].Status = "completed"
			}
		}
	}
	plan.Status = "reviewed"
	plan.PlanStatus = "reviewed"
	_ = store.PutPlan(j.ProjectID, j.SpecID, plan)
	total, done = countPlanSubtasks(plan)
	_ = store.PutProgress(j.ProjectID, j.SpecID, TaskProgress{
		Progress: pct(done, total), SubtaskCompleted: done, SubtaskTotal: total, RunID: j.RunID, CurrentPhaseName: "Review",
	})
	_, _ = store.MoveTask(j.ProjectID, j.SpecID, "human_review")
	_ = store.AppendSpecLog(j.ProjectID, j.SpecID, "validation",
		fmt.Sprintf("[%s] model review PASS (%s) → human_review\n", j.RunID, nz(rr.Model, "?")))
	return fmt.Sprintf("Review PASS (model/%s): wrote REVIEW.md; moved to human_review.", nz(rr.Model, "model")), nil
}
